In [1]:
import pip
import numpy as np
import pandas as pd
import sklearn
import tabulate
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import median_absolute_error

In [18]:
def log_errors(y_test, predicted):
    mae = mean_absolute_error(y_test, predicted)
    mse = mean_squared_error(y_test, predicted, multioutput='raw_values')
    r2 = r2_score(y_test, predicted)
    medae = median_absolute_error(y_test, predicted)
    print('mae ',mae)
    print('mse ',mse)
    print('r2 score ', r2)
    print('median_ae ',medae)

In [4]:
song_app = pd.read_csv("../../SongApp.csv",header=-1,)

In [3]:
song_app.head()

0     1         2         3         4         5         6         7   \
0  NaN  2001  49.94357  21.47114  73.07750   8.74861 -17.40628 -13.09905   
1  0.0  2001  48.73215  18.42930  70.32679  12.94636 -10.32437 -24.83777   
2  1.0  2001  50.95714  31.85602  55.81851  13.41693  -6.57898 -18.54940   
3  2.0  2001  48.24750  -1.89837  36.29772   2.58776   0.97170 -26.21683   
4  3.0  2001  50.97020  42.20998  67.09964   8.46791 -15.85279 -16.81409   

         8         9     ...           82         83        84        85  \
0 -25.01202 -12.23257    ...     13.01620  -54.40548  58.99367  15.37344   
1   8.76630  -0.92019    ...      5.66812  -19.68073  33.04964  42.87836   
2  -3.27872  -2.35035    ...      3.03800   26.05866 -50.92779  10.93792   
3   5.05097 -10.34124    ...     34.57337 -171.70734 -16.96705 -46.67617   
4 -12.48207  -9.37636    ...      9.92661  -55.95724  64.92712 -17.72522   

         86        87         88        89         90        91  
0   1.11144 -23.08793   68.40795  -1.82223  -27.46348   2.26327  
1  -9.90378 -32.22788   70.49388  12.04941   58.43453  26.92061  
2  -0.07568  43.20130 -115.00698  -0.05859   39.67068  -0.66345  
3 -12.51516  82.58061  -72.08993   9.90558  199.62971  18.85382  
4  -1.49237  -7.50035   51.76631   7.88713   55.66926  28.74903  

[5 rows x 92 columns]

In [4]:
song_app.size

42661872

In [5]:
song_app.shape

(463716, 92)

In [3]:
# clean data
df_song = song_app.dropna()
df_song.__delitem__(0)

In [5]:
df_song.head()

1         2         3         4         5         6         7         8   \
1  2001  48.73215  18.42930  70.32679  12.94636 -10.32437 -24.83777   8.76630   
2  2001  50.95714  31.85602  55.81851  13.41693  -6.57898 -18.54940  -3.27872   
3  2001  48.24750  -1.89837  36.29772   2.58776   0.97170 -26.21683   5.05097   
4  2001  50.97020  42.20998  67.09964   8.46791 -15.85279 -16.81409 -12.48207   
5  2001  50.54767   0.31568  92.35066  22.38696 -25.51870 -19.04928  20.67345   

         9         10    ...           82         83        84        85  \
1  -0.92019  18.76548    ...      5.66812  -19.68073  33.04964  42.87836   
2  -2.35035  16.07017    ...      3.03800   26.05866 -50.92779  10.93792   
3 -10.34124   3.55005    ...     34.57337 -171.70734 -16.96705 -46.67617   
4  -9.37636  12.63699    ...      9.92661  -55.95724  64.92712 -17.72522   
5  -5.19943   3.63566    ...      6.59753  -50.69577  26.02574  18.94430   

         86        87         88        89         90        91  
1  -9.90378 -32.22788   70.49388  12.04941   58.43453  26.92061  
2  -0.07568  43.20130 -115.00698  -0.05859   39.67068  -0.66345  
3 -12.51516  82.58061  -72.08993   9.90558  199.62971  18.85382  
4  -1.49237  -7.50035   51.76631   7.88713   55.66926  28.74903  
5  -0.33730   6.09352   35.18381   5.00283  -11.02257   0.02263  

[5 rows x 91 columns]

In [6]:
labels_column = df_song.iloc[0:,0]
labels = df_song.values[0:,0]
labels

array([ 2001.,  2001.,  2001., ...,  2006.,  2007.,  2007.])

In [7]:
df_song.__delitem__(1)

In [8]:
df_song['labels'] = labels_column

In [9]:
num_columns = df_song.columns.shape[0]
columns = list(range(num_columns - 1))
columns_name = list(map(str,columns)) + ['labels']
df_song.columns = columns_name
df_song.head()

0         1         2         3         4         5         6  \
1  48.73215  18.42930  70.32679  12.94636 -10.32437 -24.83777   8.76630   
2  50.95714  31.85602  55.81851  13.41693  -6.57898 -18.54940  -3.27872   
3  48.24750  -1.89837  36.29772   2.58776   0.97170 -26.21683   5.05097   
4  50.97020  42.20998  67.09964   8.46791 -15.85279 -16.81409 -12.48207   
5  50.54767   0.31568  92.35066  22.38696 -25.51870 -19.04928  20.67345   

          7         8        9   ...           81        82        83  \
1  -0.92019  18.76548  4.59210   ...    -19.68073  33.04964  42.87836   
2  -2.35035  16.07017  1.39518   ...     26.05866 -50.92779  10.93792   
3 -10.34124   3.55005 -6.36304   ...   -171.70734 -16.96705 -46.67617   
4  -9.37636  12.63699  0.93609   ...    -55.95724  64.92712 -17.72522   
5  -5.19943   3.63566 -4.69088   ...    -50.69577  26.02574  18.94430   

         84        85         86        87         88        89  labels  
1  -9.90378 -32.22788   70.49388  12.04941   58.43453  26.92061    2001  
2  -0.07568  43.20130 -115.00698  -0.05859   39.67068  -0.66345    2001  
3 -12.51516  82.58061  -72.08993   9.90558  199.62971  18.85382    2001  
4  -1.49237  -7.50035   51.76631   7.88713   55.66926  28.74903    2001  
5  -0.33730   6.09352   35.18381   5.00283  -11.02257   0.02263    2001  

[5 rows x 91 columns]

In [10]:
x_data = df_song.sample(200000)
y_data = x_data.values[0:,90]

In [11]:
y_data

array([ 1985.,  2003.,  1973., ...,  1970.,  1996.,  2000.])

In [12]:
x_data.__delitem__('labels')

In [13]:
x_data.head()

0          1         2         3         4         5         6  \
182118  33.06978 -106.17999  49.43166  -0.96195  13.79342  11.92225 -34.76520   
362247  50.52501    1.83161  19.25005  -6.53080 -22.96427 -17.40130 -13.62301   
13899   48.97373   17.20416  58.90735  10.69004   2.81439 -13.85964  10.42004   
249408  49.65950   -6.73684  29.73053   3.54555  -6.18953 -22.97819  13.73642   
140633  39.30706  -89.04387  41.34497 -14.57354  -6.99869  -4.65793 -20.90667   

               7         8         9    ...           80         81        82  \
182118   6.24186   1.08657   6.00159    ...     36.08244 -308.94203  11.98661   
362247  -4.12042  15.41976   2.33534    ...     -8.02467  -32.54531  28.52287   
13899   -5.45971   4.79168  -5.96153    ...     -7.61235  -18.78676   5.50428   
249408 -14.49794   9.25076  -6.13776    ...     -1.03556    0.06753  23.63692   
140633  -3.22535  -4.36128 -10.41963    ...      9.33406 -157.51138  48.74647   

              83       84        85        86       87        88        89  
182118  65.56685  1.80059  52.63843 -14.41618 -0.97027  53.17025  14.47587  
362247  25.91253  5.63279  25.85579 -11.52911 -1.68137   2.89554   0.91198  
13899   23.95081 -1.70662  14.78621  33.47040 -2.50299 -32.80450  -3.41999  
249408   8.13384 -0.87894  24.26714 -22.65194  3.62752  90.49192   2.90389  
140633   9.39783 -3.30607   8.84198  37.37397 -3.72342  29.21346   2.09331  

[5 rows x 90 columns]

In [14]:
# split into training and test data
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.1, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(180000, 90)
(20000, 90)
(180000,)
(20000,)


In [18]:
from sklearn.linear_model import Ridge
clf = Ridge(alpha=1.0)
clf.fit(X_train, y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [19]:
def log_errors(y_test, predicted):
    mae = mean_absolute_error(y_test, predicted)
    mse = mean_squared_error(y_test, predicted, multioutput='raw_values')
    r2 = r2_score(y_test, predicted)
    medae = median_absolute_error(y_test, predicted)
    print('mae ',mae)
    print('mse ',mse)
    print('r2 score ', r2)
    print('median_ae ',medae)

In [23]:
predicted = clf.predict(X_test)
log_errors(y_test=y_test,predicted=predicted)

mae  6.75850943926
mse  [ 90.40759727]
r2 score  0.24619819738
median_ae  4.95426164694


In [26]:
x_data = df_song.sample(200000)
y_data = x_data.values[0:,90]
y_data

array([ 1974.,  2007.,  1991., ...,  2008.,  2008.,  1994.])

In [27]:
x_data.__delitem__('labels')
x_data.head()

0         1         2         3         4         5         6  \
406937  47.31222  74.90513  44.05177  10.73617  -2.03649 -11.59924  -8.09480   
72479   47.20511  41.32909   7.14008   0.16630 -22.17595  10.41448  -8.47954   
453335  43.30716  27.37967  20.57754  -0.49069   6.27952 -18.96120  17.44111   
370076  44.49023  -2.18077   9.80220 -15.89927  -2.10767  -8.77368  -7.38963   
448145  38.31163 -48.42282  23.51060   2.68854 -41.69420 -23.51358  31.37422   

              7         8        9    ...           80         81         82  \
406937 -6.86489   1.36450 -0.77026    ...     -0.01936   -0.11310   30.67352   
72479   0.55839  -1.21455 -2.67275    ...     11.39114 -115.42766  -89.72906   
453335 -2.46593  -1.01763  0.08241    ...     -1.36843  -23.77067   28.97374   
370076 -8.10087  14.40200 -3.43089    ...    -24.36912 -206.77287  145.48395   
448145  0.55920 -23.31137 -7.31898    ...     81.92437    4.69848  351.83375   

               83        84         85         86        87         88  \
406937    9.95861  -3.03571   42.48783   -5.63397   0.66414   12.89092   
72479    79.76643  19.86439  325.11315   49.06507 -10.31000  -31.57913   
453335  -82.68325  11.75621    5.55085 -202.38492   2.35498   -8.22367   
370076  132.96415 -26.02633   59.64239   86.53208  12.97218  171.25621   
448145  -88.20193 -15.10855 -198.26318 -310.76813  -1.49511  495.87376   

              89  
406937   1.54492  
72479  -16.19791  
453335 -16.31417  
370076  47.98859  
448145  26.79823  

[5 rows x 90 columns]

In [28]:
# preprocess dataset, split into training and test part
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(x_data)

In [29]:
# split into training and test data
X_train, X_test, y_train, y_test = train_test_split(X, y_data, test_size=0.1, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(180000, 90)
(20000, 90)
(180000,)
(20000,)


In [31]:
from sklearn.linear_model import Ridge
clf = Ridge(alpha=1.0)
clf.fit(X_train, y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [32]:
predicted = clf.predict(X_test)
log_errors(y_test=y_test,predicted=predicted)

mae  6.7640819082
mse  [ 90.38999431]
r2 score  0.239938298205
median_ae  4.93242229277


In [15]:
from sklearn.linear_model import Ridge
from sklearn import linear_model
reg = linear_model.RidgeCV(alphas=[0.1, 1.0, 10.0])
reg.fit(X_train, y_train)

RidgeCV(alphas=[0.1, 1.0, 10.0], cv=None, fit_intercept=True, gcv_mode=None,
    normalize=False, scoring=None, store_cv_values=False)

In [19]:
predicted = reg.predict(X_test)
log_errors(y_test=y_test,predicted=predicted)

mae  6.78743722927
mse  [ 90.62342638]
r2 score  0.236334534267
median_ae  4.96920658783
